# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appointments_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1398, 793)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setMinimumSize(QtCore.QSize(200, 0))
        self.sidebar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sidebar.setStyleSheet("\n"
"QFrame#sidebar {\n"
"    background-color: #555555;\n"
"    border: none;\n"
"}\n"
"       ")
        self.sidebar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sidebar.setObjectName("sidebar")
        self.sidebarLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.sidebarLayout.setContentsMargins(15, 20, 15, 20)
        self.sidebarLayout.setObjectName("sidebarLayout")
        self.menuButton = QtWidgets.QPushButton(self.sidebar)
        self.menuButton.setMinimumSize(QtCore.QSize(0, 45))
        self.menuButton.setStyleSheet("QPushButton#menuButton {\n"
"    font-size: 22px;\n"
"    text-align: center;\n"
"}")
        self.menuButton.setObjectName("menuButton")
        self.sidebarLayout.addWidget(self.menuButton)
        self.dashboardButton = QtWidgets.QPushButton(self.sidebar)
        self.dashboardButton.setMinimumSize(QtCore.QSize(0, 45))
        self.dashboardButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 12px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.dashboardButton.setObjectName("dashboardButton")
        self.sidebarLayout.addWidget(self.dashboardButton)
        self.calendarButton = QtWidgets.QPushButton(self.sidebar)
        self.calendarButton.setMinimumSize(QtCore.QSize(0, 45))
        self.calendarButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 12px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.calendarButton.setObjectName("calendarButton")
        self.sidebarLayout.addWidget(self.calendarButton)
        self.propertiesButton = QtWidgets.QPushButton(self.sidebar)
        self.propertiesButton.setMinimumSize(QtCore.QSize(0, 45))
        self.propertiesButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 12px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.propertiesButton.setObjectName("propertiesButton")
        self.sidebarLayout.addWidget(self.propertiesButton)
        self.clientsButton = QtWidgets.QPushButton(self.sidebar)
        self.clientsButton.setMinimumSize(QtCore.QSize(0, 45))
        self.clientsButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 12px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.clientsButton.setObjectName("clientsButton")
        self.sidebarLayout.addWidget(self.clientsButton)
        self.salesButton = QtWidgets.QPushButton(self.sidebar)
        self.salesButton.setMinimumSize(QtCore.QSize(0, 45))
        self.salesButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 12px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.salesButton.setObjectName("salesButton")
        self.sidebarLayout.addWidget(self.salesButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.sidebarLayout.addItem(spacerItem)
        self.settingsButton = QtWidgets.QPushButton(self.sidebar)
        self.settingsButton.setMinimumSize(QtCore.QSize(0, 45))
        self.settingsButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 12px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.settingsButton.setObjectName("settingsButton")
        self.sidebarLayout.addWidget(self.settingsButton)
        self.horizontalLayout.addWidget(self.sidebar)
        self.contentArea = QtWidgets.QFrame(self.centralwidget)
        self.contentArea.setStyleSheet("\n"
"QFrame#contentArea {\n"
"    background-image: url(:/images/assests/lty_background.png);\n"
"    radius: 20;\n"
"    border: none;\n"
"}\n"
"       ")
        self.contentArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentArea.setObjectName("contentArea")
        self.contentLayout = QtWidgets.QVBoxLayout(self.contentArea)
        self.contentLayout.setContentsMargins(40, 30, 40, 30)
        self.contentLayout.setObjectName("contentLayout")
        self.contentStack = QtWidgets.QStackedWidget(self.contentArea)
        self.contentStack.setStyleSheet("QStackedWidget{\n"
"    selection-background-color: rgb(206, 206, 206);\n"
"}")
        self.contentStack.setObjectName("contentStack")
        self.dashboardPage = QtWidgets.QWidget()
        self.dashboardPage.setObjectName("dashboardPage")
        self.dashboardPageLayout = QtWidgets.QVBoxLayout(self.dashboardPage)
        self.dashboardPageLayout.setContentsMargins(0, 0, 0, 0)
        self.dashboardPageLayout.setObjectName("dashboardPageLayout")
        self.pageTitle = QtWidgets.QLabel(self.dashboardPage)
        self.pageTitle.setStyleSheet("\n"
"QLabel {\n"
"    color: #2E2E33;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"}\n"
"              ")
        self.pageTitle.setObjectName("pageTitle")
        self.dashboardPageLayout.addWidget(self.pageTitle)
        self.dateLabel = QtWidgets.QLabel(self.dashboardPage)
        self.dateLabel.setStyleSheet("\n"
"QLabel {\n"
"    color: #888888;\n"
"    font-size: 15px;\n"
"}\n"
"              ")
        self.dateLabel.setObjectName("dateLabel")
        self.dashboardPageLayout.addWidget(self.dateLabel)
        self.Appointments_listed = QtWidgets.QTextBrowser(self.dashboardPage)
        self.Appointments_listed.setObjectName("Appointments_listed")
        self.dashboardPageLayout.addWidget(self.Appointments_listed)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.dashboardPageLayout.addItem(spacerItem1)
        self.contentStack.addWidget(self.dashboardPage)
        self.calendarPage = QtWidgets.QWidget()
        self.calendarPage.setObjectName("calendarPage")
        self.calendarPageLayout = QtWidgets.QVBoxLayout(self.calendarPage)
        self.calendarPageLayout.setContentsMargins(0, 0, 0, 0)
        self.calendarPageLayout.setObjectName("calendarPageLayout")
        self.calendarPageTitle = QtWidgets.QLabel(self.calendarPage)
        self.calendarPageTitle.setStyleSheet("\n"
"QLabel {\n"
"    color: #2E2E33;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"}\n"
"              ")
        self.calendarPageTitle.setObjectName("calendarPageTitle")
        self.calendarPageLayout.addWidget(self.calendarPageTitle)
        self.calendarPageSubtitle = QtWidgets.QLabel(self.calendarPage)
        self.calendarPageSubtitle.setStyleSheet("\n"
"QLabel {\n"
"    color: #888888;\n"
"    font-size: 15px;\n"
"}\n"
"              ")
        self.calendarPageSubtitle.setObjectName("calendarPageSubtitle")
        self.calendarPageLayout.addWidget(self.calendarPageSubtitle)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.calendarPage)
        self.calendarWidget.setObjectName("calendarWidget")
        self.calendarPageLayout.addWidget(self.calendarWidget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.calendarPageLayout.addItem(spacerItem2)
        self.contentStack.addWidget(self.calendarPage)
        self.propertiesPage = QtWidgets.QWidget()
        self.propertiesPage.setObjectName("propertiesPage")
        self.propertiesPageLayout = QtWidgets.QVBoxLayout(self.propertiesPage)
        self.propertiesPageLayout.setContentsMargins(0, 0, 0, 0)
        self.propertiesPageLayout.setObjectName("propertiesPageLayout")
        self.propertiesPageTitle = QtWidgets.QLabel(self.propertiesPage)
        self.propertiesPageTitle.setStyleSheet("\n"
"QLabel {\n"
"    color: #2E2E33;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"}\n"
"              ")
        self.propertiesPageTitle.setObjectName("propertiesPageTitle")
        self.propertiesPageLayout.addWidget(self.propertiesPageTitle)
        self.propertiesPageSubtitle = QtWidgets.QLabel(self.propertiesPage)
        self.propertiesPageSubtitle.setStyleSheet("\n"
"QLabel {\n"
"    color: #888888;\n"
"    font-size: 15px;\n"
"}\n"
"              ")
        self.propertiesPageSubtitle.setObjectName("propertiesPageSubtitle")
        self.propertiesPageLayout.addWidget(self.propertiesPageSubtitle)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.propertiesPageLayout.addItem(spacerItem3)
        self.contentStack.addWidget(self.propertiesPage)
        self.clientsPage = QtWidgets.QWidget()
        self.clientsPage.setObjectName("clientsPage")
        self.clientsPageLayout = QtWidgets.QVBoxLayout(self.clientsPage)
        self.clientsPageLayout.setContentsMargins(0, 0, 0, 0)
        self.clientsPageLayout.setObjectName("clientsPageLayout")
        self.clientsPageTitle = QtWidgets.QLabel(self.clientsPage)
        self.clientsPageTitle.setStyleSheet("\n"
"QLabel {\n"
"    color: #2E2E33;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"}\n"
"              ")
        self.clientsPageTitle.setObjectName("clientsPageTitle")
        self.clientsPageLayout.addWidget(self.clientsPageTitle)
        self.clientsPageSubtitle = QtWidgets.QLabel(self.clientsPage)
        self.clientsPageSubtitle.setStyleSheet("\n"
"QLabel {\n"
"    color: #888888;\n"
"    font-size: 15px;\n"
"}\n"
"              ")
        self.clientsPageSubtitle.setObjectName("clientsPageSubtitle")
        self.clientsPageLayout.addWidget(self.clientsPageSubtitle)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.clientsPageLayout.addItem(spacerItem4)
        self.contentStack.addWidget(self.clientsPage)
        self.salesPage = QtWidgets.QWidget()
        self.salesPage.setObjectName("salesPage")
        self.salesPageLayout = QtWidgets.QVBoxLayout(self.salesPage)
        self.salesPageLayout.setContentsMargins(0, 0, 0, 0)
        self.salesPageLayout.setObjectName("salesPageLayout")
        self.salesPageTitle = QtWidgets.QLabel(self.salesPage)
        self.salesPageTitle.setStyleSheet("\n"
"QLabel {\n"
"    color: #2E2E33;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"}\n"
"              ")
        self.salesPageTitle.setObjectName("salesPageTitle")
        self.salesPageLayout.addWidget(self.salesPageTitle)
        self.salesPageSubtitle = QtWidgets.QLabel(self.salesPage)
        self.salesPageSubtitle.setStyleSheet("\n"
"QLabel {\n"
"    color: #888888;\n"
"    font-size: 15px;\n"
"}\n"
"              ")
        self.salesPageSubtitle.setObjectName("salesPageSubtitle")
        self.salesPageLayout.addWidget(self.salesPageSubtitle)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.salesPageLayout.addItem(spacerItem5)
        self.contentStack.addWidget(self.salesPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.settingsPageLayout = QtWidgets.QVBoxLayout(self.settingsPage)
        self.settingsPageLayout.setContentsMargins(0, 0, 0, 0)
        self.settingsPageLayout.setObjectName("settingsPageLayout")
        self.settingsPageTitle = QtWidgets.QLabel(self.settingsPage)
        self.settingsPageTitle.setStyleSheet("\n"
"QLabel {\n"
"    color: #2E2E33;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"}\n"
"              ")
        self.settingsPageTitle.setObjectName("settingsPageTitle")
        self.settingsPageLayout.addWidget(self.settingsPageTitle)
        self.settingsPageSubtitle = QtWidgets.QLabel(self.settingsPage)
        self.settingsPageSubtitle.setStyleSheet("\n"
"QLabel {\n"
"    color: #888888;\n"
"    font-size: 15px;\n"
"}\n"
"              ")
        self.settingsPageSubtitle.setObjectName("settingsPageSubtitle")
        self.settingsPageLayout.addWidget(self.settingsPageSubtitle)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settingsPageLayout.addItem(spacerItem6)
        self.contentStack.addWidget(self.settingsPage)
        self.contentLayout.addWidget(self.contentStack)
        self.horizontalLayout.addWidget(self.contentArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.contentStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LYT Real Estate"))
        self.menuButton.setText(_translate("MainWindow", "☰  Menu"))
        self.dashboardButton.setText(_translate("MainWindow", "Dashboard"))
        self.calendarButton.setText(_translate("MainWindow", "Calendar"))
        self.propertiesButton.setText(_translate("MainWindow", "Properties"))
        self.clientsButton.setText(_translate("MainWindow", "Clients"))
        self.salesButton.setText(_translate("MainWindow", "Sales"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.pageTitle.setText(_translate("MainWindow", "Today\'s Appointments"))
        self.dateLabel.setText(_translate("MainWindow", "12 September 2026"))
        self.calendarPageTitle.setText(_translate("MainWindow", "Calendar"))
        self.calendarPageSubtitle.setText(_translate("MainWindow", "Book appointments and property viewings."))
        self.propertiesPageTitle.setText(_translate("MainWindow", "Properties"))
        self.propertiesPageSubtitle.setText(_translate("MainWindow", "Add, view, and manage property listings."))
        self.clientsPageTitle.setText(_translate("MainWindow", "Clients"))
        self.clientsPageSubtitle.setText(_translate("MainWindow", "Add, view, and remove clients."))
        self.salesPageTitle.setText(_translate("MainWindow", "Sales"))
        self.salesPageSubtitle.setText(_translate("MainWindow", "Track deals and closed sales."))
        self.settingsPageTitle.setText(_translate("MainWindow", "Settings"))
        self.settingsPageSubtitle.setText(_translate("MainWindow", "Application settings."))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
