# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lyt_realestate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1680, 939)
        self.dialogLayout = QtWidgets.QVBoxLayout(Dialog)
        self.dialogLayout.setContentsMargins(0, 0, 0, 0)
        self.dialogLayout.setObjectName("dialogLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frameGridLayout = QtWidgets.QGridLayout(self.frame)
        self.frameGridLayout.setContentsMargins(0, 0, 0, 0)
        self.frameGridLayout.setObjectName("frameGridLayout")
        self.backgroundlabel = QtWidgets.QLabel(self.frame)
        self.backgroundlabel.setText("")
        self.backgroundlabel.setPixmap(QtGui.QPixmap("assests/lty_background.png"))
        self.backgroundlabel.setScaledContents(True)
        self.backgroundlabel.setObjectName("backgroundlabel")
        self.frameGridLayout.addWidget(self.backgroundlabel, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(370, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1: 1, y1: 0,\n"
"        x2: 0, y2: 0,\n"
"           stop: 0 rgb(211, 211, 211),\n"
"         stop: 1 rgb(150, 150, 150)\n"
"    );\n"
"    border-radius: 32px;\n"
"    border: none;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.cardLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.cardLayout.setContentsMargins(40, 32, 40, 40)
        self.cardLayout.setSpacing(20)
        self.cardLayout.setObjectName("cardLayout")
        self.login_label = QtWidgets.QTextBrowser(self.frame_2)
        self.login_label.setMinimumSize(QtCore.QSize(0, 100))
        self.login_label.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.login_label.setFont(font)
        self.login_label.setAcceptDrops(False)
        self.login_label.setStyleSheet("QTextBrowser {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 32px;\n"
"}")
        self.login_label.setObjectName("login_label")
        self.cardLayout.addWidget(self.login_label)
        self.username_txt = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(55)
        sizePolicy.setHeightForWidth(self.username_txt.sizePolicy().hasHeightForWidth())
        self.username_txt.setSizePolicy(sizePolicy)
        self.username_txt.setStyleSheet("QLineEdit{    \n"
"    background-color: rgb(159, 159, 159);\n"
"    border: none;\n"
"    border-radius: 20\n"
"}")
        self.username_txt.setObjectName("username_txt")
        self.cardLayout.addWidget(self.username_txt)
        self.password_txt = QtWidgets.QLineEdit(self.frame_2)
        self.password_txt.setStyleSheet("QLineEdit{    \n"
"    background-color: rgb(159, 159, 159);\n"
"    border: none;\n"
"    border-radius: 20\n"
"}")
        self.password_txt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_txt.setObjectName("password_txt")
        self.cardLayout.addWidget(self.password_txt)
        self.login_btn = QtWidgets.QPushButton(self.frame_2)
        self.login_btn.setStyleSheet("QPushButton {\n"
"    background-color: #555555;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 16px;\n"
"    padding: 16px;\n"
"    font-size: 22px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #444444;\n"
"}")
        self.login_btn.setObjectName("login_btn")
        self.cardLayout.addWidget(self.login_btn)
        self.frameGridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.dialogLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.login_label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:60pt; font-weight:600; font-style:italic;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt; font-weight:400; font-style:normal;\">Login</span></p></body></html>"))
        self.username_txt.setPlaceholderText(_translate("Dialog", "Username"))
        self.password_txt.setPlaceholderText(_translate("Dialog", "Password"))
        self.login_btn.setText(_translate("Dialog", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
